### PR TITLE
Unmap file if load container fails

### LINKED ISSUE #58: LoadContainer() can return an error and leave the file open/mapped
If a sif file is opened successfully, but is invalid, `LoadContainer()` will return an error, yet leaves the file open/mmapped.

### PR DESCRIPTION
**Pull request by sashayakovtseva**
Along that: 
- get rid of named return parameter in `LoadContainer` 
- call `OpenFile` once
- use mode 0  for `OpenFile` since we don't create file here and the last argument is getting ignored by the system either way (feel free to correct me if I am wrong here)
- close opened file if `LoadContainerFp` fails

Closes #58

### CODE REVIEW

File: pkg/sif/load.go [hunk 1]
```diff
@@ -120,32 +121,43 @@ func (fimg *FileImage) unmapFile() error {
 // LoadContainer is responsible for loading a SIF container file. It takes
 // the container file name, and whether the file is opened as read-only
 // as arguments.
-func LoadContainer(filename string, rdonly bool) (fimg FileImage, err error) {
-	var fp ReadWriter
+func LoadContainer(filename string, rdonly bool) (FileImage, error) {
```
Comment (jscook2345) [inline pkg/sif/load.go]: Could the `rdonly` argument be changed to `mode` and than instead pass the `os.*` values that way?

Comment (sashayakovtseva) [reply pkg/sif/load.go]: That will break API and according to semver we would need to bump sif 2.0
